# Generated by Django 4.1.7 on 2023-03-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='studentID',
            field=models.CharField(default=255, max_length=8, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
