# Generated by Django 4.1.7 on 2023-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='aboutMe',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
