# Generated by Django 4.1.7 on 2023-03-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='cv',
            field=models.ManyToManyField(to='student.cv'),
        ),
        migrations.AddField(
            model_name='skill',
            name='cv',
            field=models.ManyToManyField(to='student.cv'),
        ),
    ]
