# Generated by Django 4.1.7 on 2023-03-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_education_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='aboutMe',
        ),
    ]
