# Generated by Django 4.2.2 on 2023-08-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_fristname_remove_student_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='68797-CV', max_length=255),
        ),
    ]
