# Generated by Django 4.1.7 on 2023-03-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_student_id_student_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentID',
            new_name='student_id',
        ),
    ]
