# Generated by Django 4.1.7 on 2023-03-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_education_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvinfobase',
            name='aboutMe',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='cvinfobase',
            name='cvname',
            field=models.CharField(default='56451-CV', max_length=255),
        ),
    ]
