# Generated by Django 4.1.7 on 2023-03-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_studentid_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='studentID',
        ),
    ]
