# Generated by Django 4.2.2 on 2023-08-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_cvinfobase_cvid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvinfobase',
            name='test',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='83657-CV', max_length=255),
        ),
    ]
