# Generated by Django 4.1.7 on 2023-03-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_cvinfobase_rename_degree_education_shcoolname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='employer',
            new_name='companyName',
        ),
        migrations.RemoveField(
            model_name='cvlanguage',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='position',
        ),
        migrations.AddField(
            model_name='cvlanguage',
            name='studentID',
            field=models.CharField(default=255, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cvinfobase',
            name='studentID',
            field=models.CharField(max_length=255),
        ),
    ]
