# Generated by Django 4.1.7 on 2023-03-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_cvinfobase_aboutme_cvinfobase_cvname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvname',
            field=models.CharField(default='79333-CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
