# Generated by Django 4.2.2 on 2023-08-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_cvinfobase_test_alter_cvinfobase_cvid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvinfobase',
            old_name='test',
            new_name='testa',
        ),
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='28792-CV', max_length=255),
        ),
    ]
