# Generated by Django 4.1.7 on 2023-03-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_employer_workexperience_companyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='studentName',
        ),
        migrations.AddField(
            model_name='education',
            name='studentID',
            field=models.CharField(default=255, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CVSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
