# Generated by Django 4.1.7 on 2023-03-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_cvinfobase_cvname_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvname',
            field=models.CharField(default='17455-CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
