# Generated by Django 4.2.2 on 2023-08-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_testa_cvinfobase_testa1_alter_cvinfobase_cvid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvinfobase',
            name='testa1',
        ),
        migrations.AddField(
            model_name='student',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='71136-CV', max_length=255),
        ),
    ]
