# Generated by Django 4.1.7 on 2023-03-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_cvinfobase_cvname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvinfobase',
            name='profileIcon',
            field=models.FileField(blank='True', null='True', upload_to='team_icons'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvname',
            field=models.CharField(default='86035-CV', max_length=255),
        ),
    ]
