# Generated by Django 4.1.7 on 2023-08-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_testa_cvinfobase_testa1_alter_cvinfobase_cvid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='64572-CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='aboutMe',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
