# Generated by Django 4.1.7 on 2023-03-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_cvinfobase_profileicon_alter_cvinfobase_cvname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvname',
            field=models.CharField(default='88539-CV', max_length=255),
        ),
    ]
