# Generated by Django 4.1.7 on 2023-08-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_cvinfobase_cvid_alter_student_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='94248-CV', max_length=255),
        ),
    ]
