# Generated by Django 4.1.7 on 2023-03-24 07:32

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_cvinfobase_cvname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvname',
            field=models.CharField(default='96003-CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='cvinfobase',
            name='profileIcon',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True),
        ),
    ]
