# Generated by Django 4.1.7 on 2023-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_cvinfobase_cvname_alter_cvinfobase_profileicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvname',
            field=models.CharField(default='60828-CV', max_length=255),
        ),
    ]
