# Generated by Django 4.1.7 on 2023-03-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_cvinfobase_cvname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvname',
            field=models.CharField(default='98911-CV', max_length=255),
        ),
    ]
