# Generated by Django 4.1.7 on 2023-04-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_cvinfobase_cvname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvinfobase',
            name='cvname',
        ),
        migrations.AddField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='95251-CV', max_length=255),
        ),
    ]
