# Generated by Django 4.1.7 on 2023-08-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_student_test1_alter_cvinfobase_cvid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='87512-CV', max_length=255),
        ),
    ]
