# Generated by Django 4.1.7 on 2023-04-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_cvinfobase_cvid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvinfobase',
            name='cvName',
            field=models.CharField(default=255, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='18468-CV', max_length=255),
        ),
    ]
