# Generated by Django 4.1.7 on 2023-04-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_cvinfobase_cvid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='18114-CV', max_length=255),
        ),
    ]
