# Generated by Django 4.1.7 on 2023-08-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_student_test1_alter_cvinfobase_cvid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvinfobase',
            name='testa1',
        ),
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='55477-CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='aboutMe',
            field=models.TextField(null=True),
        ),
    ]
