# Generated by Django 4.1.7 on 2023-04-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_cvinfobase_cvid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='51150-CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
