# Generated by Django 4.1.7 on 2023-08-05 06:02

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_remove_cvinfobase_testa1_alter_cvinfobase_cvid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profileIcon',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True),
        ),
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='75453-CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='aboutMe',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
