# Generated by Django 4.2.3 on 2023-08-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_student_profileicon_alter_cvinfobase_cvid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='13963-CV', max_length=255),
        ),
        migrations.RemoveField(
            model_name='language',
            name='cv',
        ),
        migrations.AddField(
            model_name='language',
            name='cv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.cvinfobase'),
        ),
    ]
