# Generated by Django 4.1.7 on 2023-07-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_cvinfobase_cvid_alter_workexperience_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvinfobase',
            name='cvName',
        ),
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='55042-CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
