# Generated by Django 4.2.3 on 2023-08-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_cvinfobase_cvid_remove_language_cv_language_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='59488-CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.cvinfobase'),
        ),
    ]
