# Generated by Django 4.2.3 on 2023-08-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_alter_cvinfobase_cvid_alter_language_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='studentID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='27273-CV', max_length=255),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='cv',
        ),
        migrations.AddField(
            model_name='skill',
            name='cv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.cvinfobase'),
        ),
    ]
