# Generated by Django 4.1.7 on 2023-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_remove_cvinfobase_cvname_alter_cvinfobase_cvid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='85360-CV', max_length=255),
        ),
    ]
