# Generated by Django 4.2.3 on 2023-08-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_skill_studentid_alter_cvinfobase_cvid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinfobase',
            name='cvId',
            field=models.CharField(default='46145-CV', max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.cvinfobase'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
