# Generated by Django 4.2.2 on 2023-08-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=128)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('start_date', models.DateField(null=True)),
                ('duration', models.CharField(max_length=128)),
                ('salary', models.IntegerField(default=0)),
                ('job_requirement', models.CharField(max_length=512)),
                ('job_description', models.CharField(max_length=512)),
                ('application_method', models.CharField(max_length=512)),
                ('remarks', models.CharField(max_length=512)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.companyinformation')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.jobtype')),
            ],
        ),
    ]
